name: terminalworld 
url: http://terminalworld.github.io
description: Time goes on. We live. We learn.
keywords: C++, Linux, Bash, Vim, UNP 

permalink: /:year/:month/:day/:title.html
paginate: 5
paginate_path: "page:num"

markdown: kramdown 
markdown_ext: md
highlighter: rouge 
excerpt_separator: "<!--more-->"
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
lsi: false

exclude: ['README.md', '*.sh', '.*', 'scripts/', 'backup']

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

cate_icons:
  reading: "fa-book"
  linux: "fa-linux"
  web: "fa-html5"
  misc: "fa-file-text"
